"""initial schema

Revision ID: bbe9b65f6f5b
Revises: 
Create Date: 2026-08-17 21:11:21.713686
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001_initial_schema'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_expense', sa.Boolean(), nullable=False),
    sa.Column('is_income', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=48), nullable=True),
    sa.Column('color', sa.String(length=16), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('slug', name=op.f('uq_categories_slug'))
    )
    op.create_index('ix_categories_sort_order', 'categories', ['sort_order'], unique=False)
    op.create_table('extraction_accuracy_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('corpus', sa.String(length=16), nullable=False),
    sa.Column('bank_code', sa.String(length=32), nullable=True),
    sa.Column('fixture_name', sa.String(length=255), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('git_commit', sa.String(length=40), nullable=True),
    sa.Column('expected_count', sa.Integer(), nullable=False),
    sa.Column('extracted_count', sa.Integer(), nullable=False),
    sa.Column('matched_count', sa.Integer(), nullable=False),
    sa.Column('missing_transactions', sa.Integer(), nullable=False),
    sa.Column('extra_transactions', sa.Integer(), nullable=False),
    sa.Column('wrong_date', sa.Integer(), nullable=False),
    sa.Column('wrong_amount', sa.Integer(), nullable=False),
    sa.Column('wrong_direction', sa.Integer(), nullable=False),
    sa.Column('wrong_merchant', sa.Integer(), nullable=False),
    sa.Column('wrong_category', sa.Integer(), nullable=False),
    sa.Column('recall', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('precision', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('date_accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('amount_accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('direction_accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('merchant_accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('category_accuracy', sa.Numeric(precision=6, scale=5), nullable=True),
    sa.Column('reconciled', sa.Boolean(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("corpus IN ('synthetic', 'real')", name=op.f('ck_extraction_accuracy_runs_corpus_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_extraction_accuracy_runs'))
    )
    op.create_index('ix_extraction_accuracy_runs_bank', 'extraction_accuracy_runs', ['bank_code'], unique=False)
    op.create_index('ix_extraction_accuracy_runs_corpus_created', 'extraction_accuracy_runs', ['corpus', 'created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('ai_enabled', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_index('ix_tenants_deleted_at', 'tenants', ['deleted_at'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('bank_code', sa.String(length=32), nullable=False),
    sa.Column('bank_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('account_last4', sa.String(length=4), nullable=False),
    sa.Column('account_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_as_of', sa.Date(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('statement_day', sa.Integer(), nullable=True),
    sa.Column('coverage_start', sa.Date(), nullable=True),
    sa.Column('coverage_end', sa.Date(), nullable=True),
    sa.Column('last_imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("account_type IN ('savings', 'current', 'credit_card', 'wallet', 'loan')", name=op.f('ck_accounts_account_type_valid')),
    sa.CheckConstraint("status IN ('active', 'dormant', 'closed')", name=op.f('ck_accounts_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_accounts_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('tenant_id', 'account_fingerprint', name='uq_accounts_tenant_id_account_fingerprint')
    )
    op.create_index('ix_accounts_tenant_bank', 'accounts', ['tenant_id', 'bank_code'], unique=False)
    op.create_index(op.f('ix_accounts_tenant_id'), 'accounts', ['tenant_id'], unique=False)
    op.create_index('ix_accounts_tenant_status', 'accounts', ['tenant_id', 'status'], unique=False)
    op.create_table('ingestion_sources',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_type IN ('pdf_upload', 'csv', 'api', 'account_aggregator')", name=op.f('ck_ingestion_sources_source_type_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ingestion_sources_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingestion_sources'))
    )
    op.create_index(op.f('ix_ingestion_sources_tenant_id'), 'ingestion_sources', ['tenant_id'], unique=False)
    op.create_index('ix_ingestion_sources_tenant_type', 'ingestion_sources', ['tenant_id', 'source_type'], unique=False)
    op.create_table('privacy_counters',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('ai_calls_made', sa.Integer(), nullable=False),
    sa.Column('payloads_blocked', sa.Integer(), nullable=False),
    sa.Column('injections_quarantined', sa.Integer(), nullable=False),
    sa.Column('outputs_rejected', sa.Integer(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=False),
    sa.Column('output_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_inr', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_privacy_counters_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_counters')),
    sa.UniqueConstraint('tenant_id', 'day', name='uq_privacy_counters_tenant_id_day')
    )
    op.create_index('ix_privacy_counters_tenant_day', 'privacy_counters', ['tenant_id', 'day'], unique=False)
    op.create_index(op.f('ix_privacy_counters_tenant_id'), 'privacy_counters', ['tenant_id'], unique=False)
    op.create_table('subcategories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_subcategories_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subcategories')),
    sa.UniqueConstraint('category_id', 'slug', name='uq_subcategories_category_id_slug')
    )
    op.create_index('ix_subcategories_category', 'subcategories', ['category_id'], unique=False)
    op.create_table('transfer_groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('match_confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('match_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("movement_type IN ('expense', 'income', 'transfer', 'credit_card_payment', 'refund', 'salary', 'investment', 'emi', 'cash_withdrawal', 'bank_charge', 'unknown')", name=op.f('ck_transfer_groups_movement_type_valid')),
    sa.CheckConstraint('match_confidence >= 0 AND match_confidence <= 1', name=op.f('ck_transfer_groups_match_confidence_in_range')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_transfer_groups_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transfer_groups'))
    )
    op.create_index('ix_transfer_groups_tenant_date', 'transfer_groups', ['tenant_id', 'detected_on'], unique=False)
    op.create_index(op.f('ix_transfer_groups_tenant_id'), 'transfer_groups', ['tenant_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('auth_provider', sa.String(length=32), nullable=False),
    sa.Column('google_subject', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("auth_provider IN ('password', 'google')", name=op.f('ck_users_auth_provider_valid')),
    sa.CheckConstraint("role IN ('owner', 'member')", name=op.f('ck_users_role_valid')),
    sa.CheckConstraint("status IN ('active', 'suspended', 'pending_deletion')", name=op.f('ck_users_status_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_users_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email'),
    sa.UniqueConstraint('google_subject', name=op.f('uq_users_google_subject'))
    )
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_index('ix_users_tenant_status', 'users', ['tenant_id', 'status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('succeeded', sa.Boolean(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action IN ('login', 'login_failed', 'logout', 'register', 'password_change', 'statement_upload', 'statement_delete', 'statement_reprocess', 'transaction_edit', 'transaction_approve', 'rule_create', 'rule_delete', 'account_delete', 'budget_change', 'export', 'ai_toggle', 'data_delete')", name=op.f('ck_audit_logs_action_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_audit_logs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_action', 'audit_logs', ['tenant_id', 'action'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_index('ix_audit_logs_tenant_occurred', 'audit_logs', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_audit_logs_user', 'audit_logs', ['user_id', 'occurred_at'], unique=False)
    op.create_table('budgets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('period', sa.String(length=32), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('alert_threshold', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("period IN ('monthly', 'quarterly', 'annual')", name=op.f('ck_budgets_period_valid')),
    sa.CheckConstraint('alert_threshold >= 0 AND alert_threshold <= 1', name=op.f('ck_budgets_alert_threshold_in_range')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_budgets_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_budgets_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_budgets_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budgets')),
    sa.UniqueConstraint('tenant_id', 'category_id', 'period', 'starts_on', name='uq_budgets_tenant_id_category_id_period_starts_on')
    )
    op.create_index('ix_budgets_tenant_active', 'budgets', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_budgets_tenant_id'), 'budgets', ['tenant_id'], unique=False)
    op.create_table('merchants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mcc', sa.String(length=8), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('is_subscription_like', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_merchants_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_merchants_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchants')),
    sa.UniqueConstraint('slug', name=op.f('uq_merchants_slug'))
    )
    op.create_index('ix_merchants_category', 'merchants', ['category_id'], unique=False)
    op.create_index('ix_merchants_verified', 'merchants', ['is_verified'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('resource_type', sa.String(length=48), nullable=True),
    sa.Column('resource_id', sa.UUID(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('statement_processed', 'statement_failed', 'reconciliation_failed', 'review_required', 'budget_breach', 'anomaly_detected', 'subscription_renewal')", name=op.f('ck_notifications_kind_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_notifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('ix_notifications_tenant_created', 'notifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_user_unread', 'notifications', ['user_id', 'read_at'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.UUID(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotated_to', sa.UUID(), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_refresh_tokens_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index('ix_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('ix_refresh_tokens_family', 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_tenant_id'), 'refresh_tokens', ['tenant_id'], unique=False)
    op.create_index('ix_refresh_tokens_user_active', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    op.create_table('statements',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('bank_code', sa.String(length=32), nullable=True),
    sa.Column('bank_detection_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('parser_name', sa.String(length=64), nullable=True),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('opening_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('closing_balance', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('account_last4', sa.String(length=4), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trust_status', sa.String(length=32), nullable=False),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('bank_statement', 'credit_card_statement', 'unknown')", name=op.f('ck_statements_document_type_valid')),
    sa.CheckConstraint("extraction_method IS NULL OR extraction_method IN ('text_layer', 'ocr', 'hybrid')", name=op.f('ck_statements_extraction_method_valid')),
    sa.CheckConstraint("status IN ('uploaded', 'processing', 'processed', 'failed')", name=op.f('ck_statements_status_valid')),
    sa.CheckConstraint("trust_status IN ('pending', 'trusted', 'untrusted')", name=op.f('ck_statements_trust_status_valid')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_statements_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_statements_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_statements_uploaded_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statements')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_statements_storage_key')),
    sa.UniqueConstraint('tenant_id', 'file_sha256', name='uq_statements_tenant_id_file_sha256')
    )
    op.create_index('ix_statements_tenant_account', 'statements', ['tenant_id', 'account_id'], unique=False)
    op.create_index(op.f('ix_statements_tenant_id'), 'statements', ['tenant_id'], unique=False)
    op.create_index('ix_statements_tenant_period', 'statements', ['tenant_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_statements_tenant_status', 'statements', ['tenant_id', 'status'], unique=False)
    op.create_index('ix_statements_tenant_trust', 'statements', ['tenant_id', 'trust_status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('cadence', sa.String(length=32), nullable=False),
    sa.Column('cadence_stability', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('typical_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('last_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('estimated_annual_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('first_charge_on', sa.Date(), nullable=False),
    sa.Column('last_charge_on', sa.Date(), nullable=False),
    sa.Column('next_expected_on', sa.Date(), nullable=True),
    sa.Column('occurrence_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("cadence IN ('weekly', 'fortnightly', 'monthly', 'quarterly', 'half_yearly', 'annual')", name=op.f('ck_subscriptions_cadence_valid')),
    sa.CheckConstraint("status IN ('active', 'lapsed', 'cancelled')", name=op.f('ck_subscriptions_status_valid')),
    sa.CheckConstraint('cadence_stability >= 0 AND cadence_stability <= 1', name=op.f('ck_subscriptions_cadence_stability_in_range')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_subscriptions_account_id_accounts'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_subscriptions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_subscriptions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions')),
    sa.UniqueConstraint('tenant_id', 'merchant', 'cadence', name='uq_subscriptions_tenant_id_merchant_cadence')
    )
    op.create_index(op.f('ix_subscriptions_tenant_id'), 'subscriptions', ['tenant_id'], unique=False)
    op.create_index('ix_subscriptions_tenant_next', 'subscriptions', ['tenant_id', 'next_expected_on'], unique=False)
    op.create_index('ix_subscriptions_tenant_status', 'subscriptions', ['tenant_id', 'status'], unique=False)
    op.create_table('user_category_rules',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('merchant_pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('min_amount', sa.Float(), nullable=True),
    sa.Column('max_amount', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('times_applied', sa.Integer(), nullable=False),
    sa.Column('last_applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name=op.f('ck_user_category_rules_confidence_in_range')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_user_category_rules_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_user_category_rules_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_user_category_rules_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_user_category_rules_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_user_category_rules_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_category_rules')),
    sa.UniqueConstraint('tenant_id', 'merchant_pattern', 'match_type', 'account_id', name='uq_user_category_rules_tenant_pattern')
    )
    op.create_index('ix_user_category_rules_tenant_active', 'user_category_rules', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_category_rules_tenant_id'), 'user_category_rules', ['tenant_id'], unique=False)
    op.create_index('ix_user_category_rules_tenant_pattern', 'user_category_rules', ['tenant_id', 'merchant_pattern'], unique=False)
    op.create_table('merchant_aliases',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('pattern', sa.String(length=255), nullable=False),
    sa.Column('match_type', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], name=op.f('fk_merchant_aliases_merchant_id_merchants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_merchant_aliases')),
    sa.UniqueConstraint('merchant_id', 'pattern', 'match_type', name='uq_merchant_aliases_merchant_id_pattern_match_type')
    )
    op.create_index('ix_merchant_aliases_pattern', 'merchant_aliases', ['pattern'], unique=False)
    op.create_index('ix_merchant_aliases_priority', 'merchant_aliases', ['priority'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('celery_task_id', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'processing', 'extracting', 'validating', 'categorizing', 'review_required', 'completed', 'failed')", name=op.f('ck_processing_jobs_state_valid')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_processing_jobs_created_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_processing_jobs_statement_id_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_processing_jobs_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_processing_jobs'))
    )
    op.create_index('ix_processing_jobs_statement', 'processing_jobs', ['statement_id'], unique=False)
    op.create_index('ix_processing_jobs_tenant_created', 'processing_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_processing_jobs_tenant_id'), 'processing_jobs', ['tenant_id'], unique=False)
    op.create_index('ix_processing_jobs_tenant_state', 'processing_jobs', ['tenant_id', 'state'], unique=False)
    op.create_table('statement_health',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_delta_paise', sa.BigInteger(), nullable=True),
    sa.Column('reconciles', sa.Boolean(), nullable=False),
    sa.Column('total_debits', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('total_credits', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('balance_continuous', sa.Boolean(), nullable=False),
    sa.Column('first_divergent_row', sa.Integer(), nullable=True),
    sa.Column('first_divergent_page', sa.Integer(), nullable=True),
    sa.Column('pages_continuous', sa.Boolean(), nullable=False),
    sa.Column('missing_pages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('declared_transaction_count', sa.Integer(), nullable=True),
    sa.Column('extracted_transaction_count', sa.Integer(), nullable=False),
    sa.Column('ocr_page_count', sa.Integer(), nullable=False),
    sa.Column('total_page_count', sa.Integer(), nullable=False),
    sa.Column('avg_confidence_extraction', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('avg_confidence_merchant', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('avg_confidence_category', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('avg_confidence_validation', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_statement_health_statement_id_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_statement_health_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_health')),
    sa.UniqueConstraint('statement_id', name=op.f('uq_statement_health_statement_id'))
    )
    op.create_index(op.f('ix_statement_health_tenant_id'), 'statement_health', ['tenant_id'], unique=False)
    op.create_index('ix_statement_health_tenant_reconciles', 'statement_health', ['tenant_id', 'reconciles'], unique=False)
    op.create_index('ix_statement_health_tenant_statement', 'statement_health', ['tenant_id', 'statement_id'], unique=False)
    op.create_table('statement_pages',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('extraction_method', sa.String(length=32), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('table_count', sa.Integer(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('ocr_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("extraction_method IN ('text_layer', 'ocr', 'hybrid')", name=op.f('ck_statement_pages_extraction_method_valid')),
    sa.CheckConstraint('ocr_confidence >= 0 AND ocr_confidence <= 1', name=op.f('ck_statement_pages_ocr_confidence_in_range')),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_statement_pages_statement_id_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_statement_pages_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statement_pages')),
    sa.UniqueConstraint('statement_id', 'page_number', name='uq_statement_pages_statement_id_page_number')
    )
    op.create_index(op.f('ix_statement_pages_tenant_id'), 'statement_pages', ['tenant_id'], unique=False)
    op.create_index('ix_statement_pages_tenant_statement', 'statement_pages', ['tenant_id', 'statement_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('original_txn_date', sa.Date(), nullable=False),
    sa.Column('original_value_date', sa.Date(), nullable=True),
    sa.Column('original_description', sa.Text(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('original_direction', sa.String(length=16), nullable=False),
    sa.Column('original_balance_after', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('original_reference', sa.String(length=128), nullable=True),
    sa.Column('original_merchant', sa.String(length=255), nullable=True),
    sa.Column('original_payment_method', sa.String(length=32), nullable=False),
    sa.Column('original_category_id', sa.UUID(), nullable=True),
    sa.Column('original_subcategory_id', sa.UUID(), nullable=True),
    sa.Column('corrected_txn_date', sa.Date(), nullable=True),
    sa.Column('corrected_description', sa.Text(), nullable=True),
    sa.Column('corrected_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('corrected_direction', sa.String(length=16), nullable=True),
    sa.Column('corrected_merchant', sa.String(length=255), nullable=True),
    sa.Column('corrected_payment_method', sa.String(length=32), nullable=True),
    sa.Column('txn_date', sa.Date(), sa.Computed('COALESCE(corrected_txn_date, original_txn_date)', persisted=True), nullable=False),
    sa.Column('description', sa.Text(), sa.Computed('COALESCE(corrected_description, original_description)', persisted=True), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), sa.Computed('COALESCE(corrected_amount, original_amount)', persisted=True), nullable=False),
    sa.Column('direction', sa.String(length=16), sa.Computed('COALESCE(corrected_direction, original_direction)', persisted=True), nullable=False),
    sa.Column('merchant', sa.String(length=255), sa.Computed('COALESCE(corrected_merchant, original_merchant)', persisted=True), nullable=True),
    sa.Column('payment_method', sa.String(length=32), sa.Computed('COALESCE(corrected_payment_method, original_payment_method)', persisted=True), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('subcategory_id', sa.UUID(), nullable=True),
    sa.Column('category_source', sa.String(length=32), nullable=False),
    sa.Column('category_reason', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('movement_type', sa.String(length=32), nullable=False),
    sa.Column('is_expense', sa.Boolean(), nullable=False),
    sa.Column('transfer_group_id', sa.UUID(), nullable=True),
    sa.Column('confidence_extraction', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_merchant', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_category', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_validation', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('confidence_min', sa.Numeric(precision=4, scale=3), sa.Computed('LEAST(confidence_extraction, confidence_merchant, confidence_category, confidence_validation)', persisted=True), nullable=False),
    sa.Column('field_confidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('verified_by', sa.UUID(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category_source IN ('user_rule', 'verified_merchant_rule', 'deterministic_rule', 'historical_pattern', 'ai_model', 'fallback_other')", name=op.f('ck_transactions_category_source_valid')),
    sa.CheckConstraint("corrected_direction IS NULL OR corrected_direction IN ('debit', 'credit')", name=op.f('ck_transactions_corrected_direction_valid')),
    sa.CheckConstraint("corrected_payment_method IS NULL OR corrected_payment_method IN ('upi', 'neft', 'imps', 'rtgs', 'card', 'atm', 'cheque', 'ach', 'nach', 'cash', 'netbanking', 'internal', 'unknown')", name=op.f('ck_transactions_corrected_payment_method_valid')),
    sa.CheckConstraint("movement_type IN ('expense', 'income', 'transfer', 'credit_card_payment', 'refund', 'salary', 'investment', 'emi', 'cash_withdrawal', 'bank_charge', 'unknown')", name=op.f('ck_transactions_movement_type_valid')),
    sa.CheckConstraint("original_direction IN ('debit', 'credit')", name=op.f('ck_transactions_original_direction_valid')),
    sa.CheckConstraint("original_payment_method IN ('upi', 'neft', 'imps', 'rtgs', 'card', 'atm', 'cheque', 'ach', 'nach', 'cash', 'netbanking', 'internal', 'unknown')", name=op.f('ck_transactions_original_payment_method_valid')),
    sa.CheckConstraint("review_status IN ('auto_approved', 'flagged', 'review_required', 'resolved')", name=op.f('ck_transactions_review_status_valid')),
    sa.CheckConstraint('NOT is_verified OR (verified_by IS NOT NULL AND verified_at IS NOT NULL)', name=op.f('ck_transactions_verified_has_actor')),
    sa.CheckConstraint('confidence_category >= 0 AND confidence_category <= 1', name=op.f('ck_transactions_confidence_category_in_range')),
    sa.CheckConstraint('confidence_extraction >= 0 AND confidence_extraction <= 1', name=op.f('ck_transactions_confidence_extraction_in_range')),
    sa.CheckConstraint('confidence_merchant >= 0 AND confidence_merchant <= 1', name=op.f('ck_transactions_confidence_merchant_in_range')),
    sa.CheckConstraint('confidence_validation >= 0 AND confidence_validation <= 1', name=op.f('ck_transactions_confidence_validation_in_range')),
    sa.CheckConstraint('corrected_amount IS NULL OR corrected_amount >= 0', name=op.f('ck_transactions_corrected_amount_non_negative')),
    sa.CheckConstraint('original_amount >= 0', name=op.f('ck_transactions_original_amount_non_negative')),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_transactions_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_transactions_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_category_id'], ['categories.id'], name=op.f('fk_transactions_original_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['original_subcategory_id'], ['subcategories.id'], name=op.f('fk_transactions_original_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_transactions_statement_id_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subcategory_id'], ['subcategories.id'], name=op.f('fk_transactions_subcategory_id_subcategories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_transactions_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_group_id'], ['transfer_groups.id'], name=op.f('fk_transactions_transfer_group_id_transfer_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], name=op.f('fk_transactions_verified_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions')),
    sa.UniqueConstraint('tenant_id', 'account_id', 'fingerprint', name='uq_transactions_tenant_id_account_id_fingerprint')
    )
    op.create_index('ix_transactions_tenant_account_date', 'transactions', ['tenant_id', 'account_id', 'txn_date'], unique=False)
    op.create_index('ix_transactions_tenant_category_date', 'transactions', ['tenant_id', 'category_id', 'txn_date'], unique=False)
    op.create_index('ix_transactions_tenant_date', 'transactions', ['tenant_id', 'txn_date'], unique=False)
    op.create_index('ix_transactions_tenant_dedup', 'transactions', ['tenant_id', 'account_id', 'txn_date', 'amount'], unique=False)
    op.create_index('ix_transactions_tenant_expense_date', 'transactions', ['tenant_id', 'is_expense', 'txn_date'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    op.create_index('ix_transactions_tenant_merchant', 'transactions', ['tenant_id', 'merchant'], unique=False)
    op.create_index('ix_transactions_tenant_review', 'transactions', ['tenant_id', 'review_status'], unique=False)
    op.create_index('ix_transactions_tenant_statement', 'transactions', ['tenant_id', 'statement_id'], unique=False)
    op.create_index('ix_transactions_transfer_group', 'transactions', ['transfer_group_id'], unique=False)
    op.create_table('ai_classifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('fields_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('predicted_category_id', sa.UUID(), nullable=True),
    sa.Column('predicted_confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_inr', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('predicted_confidence >= 0 AND predicted_confidence <= 1', name=op.f('ck_ai_classifications_predicted_confidence_in_range')),
    sa.ForeignKeyConstraint(['predicted_category_id'], ['categories.id'], name=op.f('fk_ai_classifications_predicted_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_ai_classifications_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_ai_classifications_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_classifications'))
    )
    op.create_index('ix_ai_classifications_model', 'ai_classifications', ['provider', 'model_name'], unique=False)
    op.create_index('ix_ai_classifications_tenant_created', 'ai_classifications', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_classifications_tenant_id'), 'ai_classifications', ['tenant_id'], unique=False)
    op.create_index('ix_ai_classifications_transaction', 'ai_classifications', ['transaction_id'], unique=False)
    op.create_table('anomalies',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('detected_on', sa.Date(), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=True),
    sa.Column('observed_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('baseline_value', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('deviation_score', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('dismissed', sa.Boolean(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('amount_outlier', 'category_spike', 'merchant_first_large', 'duplicate_proximity', 'unusual_frequency')", name=op.f('ck_anomalies_kind_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_anomalies_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_anomalies_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_anomalies_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_anomalies'))
    )
    op.create_index('ix_anomalies_tenant_detected', 'anomalies', ['tenant_id', 'detected_on'], unique=False)
    op.create_index(op.f('ix_anomalies_tenant_id'), 'anomalies', ['tenant_id'], unique=False)
    op.create_index('ix_anomalies_tenant_kind', 'anomalies', ['tenant_id', 'kind'], unique=False)
    op.create_index('ix_anomalies_transaction', 'anomalies', ['transaction_id'], unique=False)
    op.create_table('insight_snapshots',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('period_month', sa.Date(), nullable=False),
    sa.Column('total_expenses', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('total_income', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('net_cash_flow', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('savings_rate', sa.Numeric(precision=4, scale=3), nullable=False),
    sa.Column('largest_category_id', sa.UUID(), nullable=True),
    sa.Column('fastest_growing_category_id', sa.UUID(), nullable=True),
    sa.Column('largest_transaction_id', sa.UUID(), nullable=True),
    sa.Column('transaction_count', sa.Integer(), nullable=False),
    sa.Column('unreviewed_count', sa.Integer(), nullable=False),
    sa.Column('untrusted_statement_count', sa.Integer(), nullable=False),
    sa.Column('breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('narrative_model', sa.String(length=64), nullable=True),
    sa.Column('narrative_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('savings_rate >= 0 AND savings_rate <= 1', name=op.f('ck_insight_snapshots_savings_rate_in_range')),
    sa.ForeignKeyConstraint(['fastest_growing_category_id'], ['categories.id'], name=op.f('fk_insight_snapshots_fastest_growing_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['largest_category_id'], ['categories.id'], name=op.f('fk_insight_snapshots_largest_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['largest_transaction_id'], ['transactions.id'], name=op.f('fk_insight_snapshots_largest_transaction_id_transactions'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_insight_snapshots_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_insight_snapshots')),
    sa.UniqueConstraint('tenant_id', 'period_month', name='uq_insight_snapshots_tenant_id_period_month')
    )
    op.create_index(op.f('ix_insight_snapshots_tenant_id'), 'insight_snapshots', ['tenant_id'], unique=False)
    op.create_index('ix_insight_snapshots_tenant_month', 'insight_snapshots', ['tenant_id', 'period_month'], unique=False)
    op.create_table('job_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.CheckConstraint("state IN ('queued', 'processing', 'extracting', 'validating', 'categorizing', 'review_required', 'completed', 'failed')", name=op.f('ck_job_events_state_valid')),
    sa.ForeignKeyConstraint(['job_id'], ['processing_jobs.id'], name=op.f('fk_job_events_job_id_processing_jobs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_job_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_events'))
    )
    op.create_index('ix_job_events_job_occurred', 'job_events', ['job_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_job_events_tenant_id'), 'job_events', ['tenant_id'], unique=False)
    op.create_index('ix_job_events_tenant_occurred', 'job_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_table('privacy_incidents',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('detector', sa.String(length=48), nullable=True),
    sa.Column('field_name', sa.String(length=64), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('model_name', sa.String(length=64), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('pii_in_payload', 'injection_quarantined', 'output_pii_echo', 'output_schema_violation', 'budget_exceeded')", name=op.f('ck_privacy_incidents_kind_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_privacy_incidents_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_privacy_incidents_transaction_id_transactions'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_privacy_incidents'))
    )
    op.create_index('ix_privacy_incidents_tenant_created', 'privacy_incidents', ['tenant_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_privacy_incidents_tenant_id'), 'privacy_incidents', ['tenant_id'], unique=False)
    op.create_index('ix_privacy_incidents_tenant_kind', 'privacy_incidents', ['tenant_id', 'kind'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.String(length=48), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('transaction_id', sa.UUID(), nullable=True),
    sa.Column('statement_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('transaction', 'large_transaction', 'statement_import', 'budget_breach', 'subscription_renewal', 'anomaly')", name=op.f('ck_timeline_events_kind_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_timeline_events_category_id_categories'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['statement_id'], ['statements.id'], name=op.f('fk_timeline_events_statement_id_statements'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_timeline_events_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_timeline_events_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_tenant_id'), 'timeline_events', ['tenant_id'], unique=False)
    op.create_index('ix_timeline_events_tenant_kind', 'timeline_events', ['tenant_id', 'kind'], unique=False)
    op.create_index('ix_timeline_events_tenant_occurred', 'timeline_events', ['tenant_id', 'occurred_on'], unique=False)
    op.create_table('transaction_audit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('actor_kind', sa.String(length=16), nullable=False),
    sa.Column('field_name', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_transaction_audit_changed_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_transaction_audit_tenant_id_tenants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_transaction_audit_transaction_id_transactions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_audit'))
    )
    op.create_index('ix_transaction_audit_tenant_changed', 'transaction_audit', ['tenant_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_transaction_audit_tenant_id'), 'transaction_audit', ['tenant_id'], unique=False)
    op.create_index('ix_transaction_audit_transaction', 'transaction_audit', ['transaction_id', 'changed_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_transaction_audit_transaction', table_name='transaction_audit')
    op.drop_index(op.f('ix_transaction_audit_tenant_id'), table_name='transaction_audit')
    op.drop_index('ix_transaction_audit_tenant_changed', table_name='transaction_audit')
    op.drop_table('transaction_audit')
    op.drop_index('ix_timeline_events_tenant_occurred', table_name='timeline_events')
    op.drop_index('ix_timeline_events_tenant_kind', table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_tenant_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index('ix_privacy_incidents_tenant_kind', table_name='privacy_incidents')
    op.drop_index(op.f('ix_privacy_incidents_tenant_id'), table_name='privacy_incidents')
    op.drop_index('ix_privacy_incidents_tenant_created', table_name='privacy_incidents')
    op.drop_table('privacy_incidents')
    op.drop_index('ix_job_events_tenant_occurred', table_name='job_events')
    op.drop_index(op.f('ix_job_events_tenant_id'), table_name='job_events')
    op.drop_index('ix_job_events_job_occurred', table_name='job_events')
    op.drop_table('job_events')
    op.drop_index('ix_insight_snapshots_tenant_month', table_name='insight_snapshots')
    op.drop_index(op.f('ix_insight_snapshots_tenant_id'), table_name='insight_snapshots')
    op.drop_table('insight_snapshots')
    op.drop_index('ix_anomalies_transaction', table_name='anomalies')
    op.drop_index('ix_anomalies_tenant_kind', table_name='anomalies')
    op.drop_index(op.f('ix_anomalies_tenant_id'), table_name='anomalies')
    op.drop_index('ix_anomalies_tenant_detected', table_name='anomalies')
    op.drop_table('anomalies')
    op.drop_index('ix_ai_classifications_transaction', table_name='ai_classifications')
    op.drop_index(op.f('ix_ai_classifications_tenant_id'), table_name='ai_classifications')
    op.drop_index('ix_ai_classifications_tenant_created', table_name='ai_classifications')
    op.drop_index('ix_ai_classifications_model', table_name='ai_classifications')
    op.drop_table('ai_classifications')
    op.drop_index('ix_transactions_transfer_group', table_name='transactions')
    op.drop_index('ix_transactions_tenant_statement', table_name='transactions')
    op.drop_index('ix_transactions_tenant_review', table_name='transactions')
    op.drop_index('ix_transactions_tenant_merchant', table_name='transactions')
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index('ix_transactions_tenant_expense_date', table_name='transactions')
    op.drop_index('ix_transactions_tenant_dedup', table_name='transactions')
    op.drop_index('ix_transactions_tenant_date', table_name='transactions')
    op.drop_index('ix_transactions_tenant_category_date', table_name='transactions')
    op.drop_index('ix_transactions_tenant_account_date', table_name='transactions')
    op.drop_table('transactions')
    op.drop_index('ix_statement_pages_tenant_statement', table_name='statement_pages')
    op.drop_index(op.f('ix_statement_pages_tenant_id'), table_name='statement_pages')
    op.drop_table('statement_pages')
    op.drop_index('ix_statement_health_tenant_statement', table_name='statement_health')
    op.drop_index('ix_statement_health_tenant_reconciles', table_name='statement_health')
    op.drop_index(op.f('ix_statement_health_tenant_id'), table_name='statement_health')
    op.drop_table('statement_health')
    op.drop_index('ix_processing_jobs_tenant_state', table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_tenant_id'), table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_tenant_created', table_name='processing_jobs')
    op.drop_index('ix_processing_jobs_statement', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index('ix_merchant_aliases_priority', table_name='merchant_aliases')
    op.drop_index('ix_merchant_aliases_pattern', table_name='merchant_aliases')
    op.drop_table('merchant_aliases')
    op.drop_index('ix_user_category_rules_tenant_pattern', table_name='user_category_rules')
    op.drop_index(op.f('ix_user_category_rules_tenant_id'), table_name='user_category_rules')
    op.drop_index('ix_user_category_rules_tenant_active', table_name='user_category_rules')
    op.drop_table('user_category_rules')
    op.drop_index('ix_subscriptions_tenant_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_tenant_next', table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_tenant_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index('ix_statements_tenant_trust', table_name='statements')
    op.drop_index('ix_statements_tenant_status', table_name='statements')
    op.drop_index('ix_statements_tenant_period', table_name='statements')
    op.drop_index(op.f('ix_statements_tenant_id'), table_name='statements')
    op.drop_index('ix_statements_tenant_account', table_name='statements')
    op.drop_table('statements')
    op.drop_index('ix_refresh_tokens_user_active', table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_tenant_id'), table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_family', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_notifications_user_unread', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('ix_notifications_tenant_created', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_merchants_verified', table_name='merchants')
    op.drop_index('ix_merchants_category', table_name='merchants')
    op.drop_table('merchants')
    op.drop_index(op.f('ix_budgets_tenant_id'), table_name='budgets')
    op.drop_index('ix_budgets_tenant_active', table_name='budgets')
    op.drop_table('budgets')
    op.drop_index('ix_audit_logs_user', table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_occurred', table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_tenant_action', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_users_tenant_status', table_name='users')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_transfer_groups_tenant_id'), table_name='transfer_groups')
    op.drop_index('ix_transfer_groups_tenant_date', table_name='transfer_groups')
    op.drop_table('transfer_groups')
    op.drop_index('ix_subcategories_category', table_name='subcategories')
    op.drop_table('subcategories')
    op.drop_index(op.f('ix_privacy_counters_tenant_id'), table_name='privacy_counters')
    op.drop_index('ix_privacy_counters_tenant_day', table_name='privacy_counters')
    op.drop_table('privacy_counters')
    op.drop_index('ix_ingestion_sources_tenant_type', table_name='ingestion_sources')
    op.drop_index(op.f('ix_ingestion_sources_tenant_id'), table_name='ingestion_sources')
    op.drop_table('ingestion_sources')
    op.drop_index('ix_accounts_tenant_status', table_name='accounts')
    op.drop_index(op.f('ix_accounts_tenant_id'), table_name='accounts')
    op.drop_index('ix_accounts_tenant_bank', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_tenants_deleted_at', table_name='tenants')
    op.drop_table('tenants')
    op.drop_index('ix_extraction_accuracy_runs_corpus_created', table_name='extraction_accuracy_runs')
    op.drop_index('ix_extraction_accuracy_runs_bank', table_name='extraction_accuracy_runs')
    op.drop_table('extraction_accuracy_runs')
    op.drop_index('ix_categories_sort_order', table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
