"""Mirror Python column defaults into database DEFAULTs

A NOT NULL column whose default lives only in SQLAlchemy is a NOT NULL
violation waiting for the first raw INSERT, COPY or psql session. This adds the
matching DEFAULT in the database for every such column, so the schema is
correct regardless of which client writes to it.

Revision ID: 25a957a6f325
Revises: 0002_rls_and_triggers
Create Date: 2026-08-17 21:25:33.618477
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0003_server_defaults'
down_revision: str | None = '0002_rls_and_triggers'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('accounts', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'active'"),
               existing_nullable=False)
    op.alter_column('ai_classifications', 'accepted',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('anomalies', 'dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('audit_logs', 'succeeded',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('budgets', 'period',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'monthly'"),
               existing_nullable=False)
    op.alter_column('budgets', 'alert_threshold',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=sa.text('0.800'),
               existing_nullable=False)
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('categories', 'is_expense',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('categories', 'is_income',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('categories', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'expected_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'extracted_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'matched_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'missing_transactions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'extra_transactions',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_date',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_amount',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_direction',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_merchant',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_category',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'reconciled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'passed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('ingestion_sources', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pdf_upload'"),
               existing_nullable=False)
    op.alter_column('ingestion_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'transaction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'unreviewed_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'untrusted_statement_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('job_events', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('merchant_aliases', 'match_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'contains'"),
               existing_nullable=False)
    op.alter_column('merchant_aliases', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('merchants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('merchants', 'is_subscription_like',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'ai_calls_made',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'payloads_blocked',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'injections_quarantined',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'outputs_rejected',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('privacy_counters', 'cost_inr',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'state',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'queued'"),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('processing_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=sa.text('3'),
               existing_nullable=False)
    op.alter_column('statement_health', 'reconciles',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('statement_health', 'balance_continuous',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('statement_health', 'pages_continuous',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('statement_health', 'extracted_transaction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statement_health', 'ocr_page_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statement_health', 'total_page_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statement_pages', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statement_pages', 'table_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statement_pages', 'row_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statements', 'document_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'unknown'"),
               existing_nullable=False)
    op.alter_column('statements', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'uploaded'"),
               existing_nullable=False)
    op.alter_column('statements', 'trust_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
    op.alter_column('statements', 'transaction_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('statements', 'duplicate_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subcategories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'occurrence_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'active'"),
               existing_nullable=False)
    op.alter_column('subscriptions', 'dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tenants', 'ai_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('transactions', 'original_payment_method',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'unknown'"),
               existing_nullable=False)
    op.alter_column('transactions', 'category_source',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'fallback_other'"),
               existing_nullable=False)
    op.alter_column('transactions', 'movement_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'unknown'"),
               existing_nullable=False)
    op.alter_column('transactions', 'is_expense',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('transactions', 'review_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'review_required'"),
               existing_nullable=False)
    op.alter_column('transactions', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_category_rules', 'match_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=sa.text("'exact'"),
               existing_nullable=False)
    op.alter_column('user_category_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('user_category_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=sa.text('100'),
               existing_nullable=False)
    op.alter_column('user_category_rules', 'times_applied',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('user_category_rules', 'confidence',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=sa.text('1.0'),
               existing_nullable=False)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'password'"),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'owner'"),
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=sa.text("'active'"),
               existing_nullable=False)
    op.alter_column('users', 'failed_login_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'failed_login_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'auth_provider',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_category_rules', 'confidence',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_category_rules', 'times_applied',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_category_rules', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_category_rules', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_category_rules', 'match_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'review_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'is_expense',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'movement_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'category_source',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('transactions', 'original_payment_method',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tenants', 'ai_enabled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'occurrence_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subcategories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statements', 'duplicate_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statements', 'transaction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statements', 'trust_status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statements', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statements', 'document_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_pages', 'row_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_pages', 'table_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_pages', 'char_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'total_page_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'ocr_page_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'extracted_transaction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'pages_continuous',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'balance_continuous',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('statement_health', 'reconciles',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_jobs', 'max_attempts',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_jobs', 'attempt',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_jobs', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('processing_jobs', 'state',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'cost_inr',
               existing_type=sa.NUMERIC(precision=12, scale=6),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'output_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'input_tokens',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'outputs_rejected',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'injections_quarantined',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'payloads_blocked',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('privacy_counters', 'ai_calls_made',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('merchants', 'is_subscription_like',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('merchants', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('merchant_aliases', 'priority',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('merchant_aliases', 'match_type',
               existing_type=sa.VARCHAR(length=16),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_events', 'progress',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'untrusted_statement_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'unreviewed_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insight_snapshots', 'transaction_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_sources', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ingestion_sources', 'source_type',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'passed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'reconciled',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_category',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_merchant',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_direction',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_amount',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'wrong_date',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'extra_transactions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'missing_transactions',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'matched_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'extracted_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('extraction_accuracy_runs', 'expected_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'sort_order',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'is_system',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'is_income',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('categories', 'is_expense',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budgets', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budgets', 'alert_threshold',
               existing_type=sa.NUMERIC(precision=4, scale=3),
               server_default=None,
               existing_nullable=False)
    op.alter_column('budgets', 'period',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    op.alter_column('audit_logs', 'succeeded',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('anomalies', 'dismissed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('ai_classifications', 'accepted',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('accounts', 'status',
               existing_type=sa.VARCHAR(length=32),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###
