"""Rule amount thresholds from float to NUMERIC

min_amount and max_amount are rupee thresholds compared against transaction
amounts. Declared as float they would make a rule match or miss unpredictably at
its own boundary — the "over Rs 5,000" rule failing on a Rs 5,000.00 charge.
Caught by tests/security/test_schema_invariants.py.

Revision ID: 7305a537419e
Revises: 0004_audit_purge_path
Create Date: 2026-08-17 21:28:04.698208
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0005_rule_thresholds_numeric'
down_revision: str | None = '0004_audit_purge_path'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_category_rules', 'min_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    op.alter_column('user_category_rules', 'max_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_category_rules', 'max_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('user_category_rules', 'min_amount',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    # ### end Alembic commands ###
